version: '3'

services:
  go-cookie-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      COOKIE_NAME: "custom_cookie"
