version: '3'

services:
  cookie:
    container_name: cookie
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - my_network


networks:
  my_network:
    driver: bridge
