# Generated by Django 4.2.7 on 2023-11-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('file_name', models.CharField(max_length=20)),
            ],
        ),
    ]
