# Generated by Django 4.2.7 on 2023-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='file_name',
            field=models.CharField(max_length=40),
        ),
    ]
