# Generated by Django 4.2.7 on 2023-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0002_alter_analytics_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='file_name',
        ),
        migrations.AddField(
            model_name='analytics',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
