# Generated by Django 4.2.7 on 2023-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0005_alter_analytics_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='image',
            field=models.BinaryField(),
        ),
    ]
