# Generated by Django 4.2.7 on 2023-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0006_alter_analytics_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='sum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
