CREATE DATABASE IF NOT EXISTS appDB;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT,DELETE ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;
CREATE TABLE IF NOT EXISTS student(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(50) NOT NULL,
  `group` VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID)
);
