version: '3'

services:
  cookie:
    container_name: mongo_app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    ports:
      - "27017:27017"
    networks:
      - my_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./.deploy/development:/etc/nginx/conf.d
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
