// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/protobuf/de_logic.proto

package de_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Input struct {
	Val1                 int32    `protobuf:"varint,1,opt,name=val1,proto3" json:"val1,omitempty"`
	Val2                 int32    `protobuf:"varint,2,opt,name=val2,proto3" json:"val2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_633d806707769508, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetVal1() int32 {
	if m != nil {
		return m.Val1
	}
	return 0
}

func (m *Input) GetVal2() int32 {
	if m != nil {
		return m.Val2
	}
	return 0
}

type Result struct {
	Val                  int32    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_633d806707769508, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetVal() int32 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterType((*Input)(nil), "de_mult.Input")
	proto.RegisterType((*Result)(nil), "de_mult.Result")
}

func init() { proto.RegisterFile("grpc/protobuf/de_logic.proto", fileDescriptor_633d806707769508) }

var fileDescriptor_633d806707769508 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0x49, 0x8d, 0xcf, 0xc9, 0x4f,
	0xcf, 0x4c, 0xd6, 0x03, 0x8b, 0x08, 0xb1, 0xa7, 0xa4, 0xc6, 0xe7, 0x96, 0xe6, 0x94, 0x28, 0xe9,
	0x73, 0xb1, 0x7a, 0xe6, 0x15, 0x94, 0x96, 0x08, 0x09, 0x71, 0xb1, 0x94, 0x25, 0xe6, 0x18, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x50, 0x31, 0x23, 0x09, 0x26, 0xb8, 0x98, 0x91,
	0x92, 0x14, 0x17, 0x5b, 0x50, 0x6a, 0x71, 0x69, 0x4e, 0x89, 0x90, 0x00, 0x17, 0x73, 0x59, 0x62,
	0x0e, 0x54, 0x03, 0x88, 0x69, 0x64, 0xca, 0xc5, 0x01, 0xb3, 0x47, 0x48, 0x93, 0x8b, 0xc5, 0x39,
	0x31, 0x27, 0x59, 0x88, 0x4f, 0x0f, 0x6a, 0x95, 0x1e, 0xd8, 0x1e, 0x29, 0x7e, 0x38, 0x1f, 0x62,
	0x8c, 0x12, 0x83, 0x13, 0x77, 0x14, 0xa7, 0x9e, 0x3e, 0x54, 0x34, 0x89, 0x0d, 0xec, 0x40, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x8b, 0x00, 0xd7, 0xc0, 0x00, 0x00, 0x00,
}
